### ISSUE TITLE
Swap out apache license for MIT and remove personal copyright

### ISSUE THREAD

**Issue by alexberriman** [peterboyer/esresult#18]
## Why?

Error handling is critical and generally tightly coupled with the rest of your code. If I were to roll `esresult` throughout my codebase, there would be a large dependency on it. Because of this, I would want as nonrestrictive a license as possible, particularly if I were evaluating a fairly new library without a lot of usage/stars. I would be more comfortable using a new library like this were it to have an MIT license.

**Comment by peterboyer** [comment]
At a glance Apache and MIT look moreorless functionally equivalent. The only main difference being that derivatives need to state changes, whereas MIT is more of a "go for it, do anything, just keep this license and copyright"

Suppose it's fair enough to switch to MIT, would be more attractive for everyone to use and repurpose/improve etc.
